## Numpy Library

    * Processing N-Dimensional arrays

In [31]:
import numpy as np

li=[1,2,3]

a=np.array(li)
b=np.arange(15)
print(b)
b.reshape(5,3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [21]:
rn=np.random.randint(0,100,size=10)
rn=np.random.randint(0,100,size=(3,4))
rn=np.random.randint(0,100+1,size=(3,3,3,3))
rn

array([[[[30, 34, 91],
         [ 9, 93, 66],
         [82, 28, 67]],

        [[43, 17, 14],
         [52, 82, 43],
         [77, 17, 51]],

        [[61,  1, 49],
         [43,  1, 91],
         [97, 47, 79]]],


       [[[58, 75, 77],
         [ 8, 14, 39],
         [35, 70, 79]],

        [[96, 67, 14],
         [53, 50, 83],
         [ 2, 24, 31]],

        [[45, 84,  9],
         [43, 27, 38],
         [35,  3, 72]]],


       [[[71, 57, 88],
         [20, 39, 67],
         [10, 33, 38]],

        [[32,  8, 92],
         [56, 43, 10],
         [ 3, 76, 79]],

        [[75, 42, 97],
         [43, 88, 86],
         [31, 53, 96]]]])

In [28]:

rn.ndim # Represents the dimension of an matrix
rn.size # Represents the no.of elements in an given dimensional array
rn.shape # represents the shape of the matrix (3,3,3,3)
rn.dtype 
rn.itemsize
rn.nbytes

324

In [29]:
rn[:2.:3]

TypeError: slice indices must be integers or None or have an __index__ method

In [55]:
import numpy as np

a=np.arange(25).reshape(5,5)
print(a)
a.shape
a.ndim

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


2

## Pandas

- Data Cleaning
- Data Analysis
- Data Transformation

### Notations
 * Data Frames
 

In [70]:
import pandas as pd

internal1={'s1':21,'s2':18,'s3':24}
internal1=pd.Series(internal1)
internal1

internal2={'s1':11,'s2':32,'s3':34}
internal2=pd.Series(internal2)
internal2

s1    11
s2    32
s3    34
dtype: int64

In [71]:
final={'Internal1': internal1,'Internal2':internal2}
final=pd.DataFrame(final)
final['Internal1']

s1    21
s2    18
s3    24
Name: Internal1, dtype: int64

In [72]:
final.columns  # Names of all columns

Index(['Internal1', 'Internal2'], dtype='object')

In [73]:
final.values  # Lists of all rows

array([[21, 11],
       [18, 32],
       [24, 34]], dtype=int64)

In [78]:
for row in final.values:
    print('Internal1 - ',row[0],',Internal2 - ', row[1])

Internal1 -  21 ,Internal2 -  11
Internal1 -  18 ,Internal2 -  32
Internal1 -  24 ,Internal2 -  34


In [82]:
final.loc['s4']=[15,19]
final

Internal1  Internal2
s1         21         11
s2         18         32
s3         24         34
s4         15         19

In [83]:
final=final.drop('s4')

In [84]:
final

Internal1  Internal2
s1         21         11
s2         18         32
s3         24         34

In [86]:
final.values[2]=[25,23]
final

Internal1  Internal2
s1         21         11
s2         18         32
s3         25         23

In [2]:
# Reading csv filedata
import pandas as pd
filepath='DataFiles/income.csv'
incomedf=pd.read_csv(filepath)
incomedf

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  47215  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [3]:
for row in incomedf.values:
    print(row[1],':',row[-1])

Alabama : 41381
Alaska : 61137
Arizona : 50602
Arkansas : 39919
California : 57528


In [4]:
sum=0
for i in range(2,11):
    sum+=incomedf.values[2][i]
sum/len(incomedf.values[2][2:])

47214.77777777778

In [5]:
# Average income of all states in year 2012
summ=0
for row in incomedf.values:
    summ+=row[-2]
sum/len(incomedf.values)

84986.6